p8105\_hw1\_sl5010
================

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

    ## ✓ ggplot2 3.3.5     ✓ purrr   0.3.4
    ## ✓ tibble  3.1.4     ✓ dplyr   1.0.7
    ## ✓ tidyr   1.1.3     ✓ stringr 1.4.0
    ## ✓ readr   2.0.1     ✓ forcats 0.5.1

    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

## Problem 1

``` r
df1 = tibble(
norm_sample = rnorm(10),
logical_vector= norm_sample >0,
vec_char = c("a", "b", "c", "d","e", "f", "g", "h","i","j"),
vec_factor = factor(c("cat", "dog", "bird", "cat", "dog", "bird", "cat", "dog", "bird", "bird"))
)

df1
```

    ## # A tibble: 10 × 4
    ##    norm_sample logical_vector vec_char vec_factor
    ##          <dbl> <lgl>          <chr>    <fct>     
    ##  1      -0.424 FALSE          a        cat       
    ##  2      -0.247 FALSE          b        dog       
    ##  3      -1.12  FALSE          c        bird      
    ##  4      -0.259 FALSE          d        cat       
    ##  5      -0.696 FALSE          e        dog       
    ##  6      -3.59  FALSE          f        bird      
    ##  7      -2.09  FALSE          g        cat       
    ##  8       0.572 TRUE           h        dog       
    ##  9       0.432 TRUE           i        bird      
    ## 10       0.613 TRUE           j        bird

``` r
mean(pull(df1,norm_sample))
```

    ## [1] -0.6811545

``` r
mean(pull(df1,logical_vector))
```

    ## [1] 0.3

``` r
mean(pull(df1,vec_char))
```

    ## Warning in mean.default(pull(df1, vec_char)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(df1,vec_factor))
```

    ## Warning in mean.default(pull(df1, vec_factor)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

Answer: mean of each first two variable (norm\_sample, logical\_vector)
works, whereas the following two variable (vec\_char, vec\_factor)
doesn’t work

    ##  [1] 0 0 0 0 0 0 0 1 1 1

    ## Warning: NAs introduced by coercion

    ##  [1] NA NA NA NA NA NA NA NA NA NA

    ##  [1] 2 3 1 2 3 1 2 3 1 1

### What happens? Why?

The logical vector become 0 and 1, true represents 1 and false
represents 0. Since their values was setted as 0 and 1 in the R language
base. Character Variable become NA, that is, they are not able to be
transform to numeric Variable. Since character could not be assigned
values. Factor Variable becomes 1,2 and 3. Since there are only 3 level
factors.

### Does this help explain what happens when you try to take the mean?

**Yes.**Since mean can only be taken for numeric values, and the logical
vector can be transfered to numeric, norm\_sample was setted to be
numeric. However, Character Variable and Factor Variable can not be
assigned numeric values, they do not have mean.

## Problem 2

``` r
## load the penguins dataset
data("penguins", package = "palmerpenguins")
```

``` r
head(penguins)
```

    ## # A tibble: 6 × 8
    ##   species island bill_length_mm bill_depth_mm flipper_length_… body_mass_g sex  
    ##   <fct>   <fct>           <dbl>         <dbl>            <int>       <int> <fct>
    ## 1 Adelie  Torge…           39.1          18.7              181        3750 male 
    ## 2 Adelie  Torge…           39.5          17.4              186        3800 fema…
    ## 3 Adelie  Torge…           40.3          18                195        3250 fema…
    ## 4 Adelie  Torge…           NA            NA                 NA          NA <NA> 
    ## 5 Adelie  Torge…           36.7          19.3              193        3450 fema…
    ## 6 Adelie  Torge…           39.3          20.6              190        3650 male 
    ## # … with 1 more variable: year <int>

``` r
## the data in this dataset, including names / values of important variables
names(penguins)
```

    ## [1] "species"           "island"            "bill_length_mm"   
    ## [4] "bill_depth_mm"     "flipper_length_mm" "body_mass_g"      
    ## [7] "sex"               "year"

``` r
skimr::skim(penguins)
```

|                                                  |          |
|:-------------------------------------------------|:---------|
| Name                                             | penguins |
| Number of rows                                   | 344      |
| Number of columns                                | 8        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |          |
| Column type frequency:                           |          |
| factor                                           | 3        |
| numeric                                          | 5        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |          |
| Group variables                                  | None     |

Data summary

**Variable type: factor**

| skim\_variable | n\_missing | complete\_rate | ordered | n\_unique | top\_counts                 |
|:---------------|-----------:|---------------:|:--------|----------:|:----------------------------|
| species        |          0 |           1.00 | FALSE   |         3 | Ade: 152, Gen: 124, Chi: 68 |
| island         |          0 |           1.00 | FALSE   |         3 | Bis: 168, Dre: 124, Tor: 52 |
| sex            |         11 |           0.97 | FALSE   |         2 | mal: 168, fem: 165          |

**Variable type: numeric**

| skim\_variable      | n\_missing | complete\_rate |    mean |     sd |     p0 |     p25 |     p50 |    p75 |   p100 | hist  |
|:--------------------|-----------:|---------------:|--------:|-------:|-------:|--------:|--------:|-------:|-------:|:------|
| bill\_length\_mm    |          2 |           0.99 |   43.92 |   5.46 |   32.1 |   39.23 |   44.45 |   48.5 |   59.6 | ▃▇▇▆▁ |
| bill\_depth\_mm     |          2 |           0.99 |   17.15 |   1.97 |   13.1 |   15.60 |   17.30 |   18.7 |   21.5 | ▅▅▇▇▂ |
| flipper\_length\_mm |          2 |           0.99 |  200.92 |  14.06 |  172.0 |  190.00 |  197.00 |  213.0 |  231.0 | ▂▇▃▅▂ |
| body\_mass\_g       |          2 |           0.99 | 4201.75 | 801.95 | 2700.0 | 3550.00 | 4050.00 | 4750.0 | 6300.0 | ▃▇▆▃▂ |
| year                |          0 |           1.00 | 2008.03 |   0.82 | 2007.0 | 2007.00 | 2008.00 | 2009.0 | 2009.0 | ▇▁▇▁▇ |

``` r
## the size of the dataset (using nrow and ncol)
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

## short description

names of important variables: “species” “island”, “bill\_length\_mm”,
“bill\_depth\_mm”, “flipper\_length\_mm”, “body\_mass\_g”, “sex”,
“year”. There are **8 variables** in total. the size of the dataset:
There are **344** rows and **8** columns in the dataset the mean flipper
length: **201.** (It is from the output of skimr::skim(penguins))

## scatterplot

``` r
## scatterplot of x and y
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm,color = species)) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8150_hw1_sl5010_files/figure-gfm/unnamed-chunk-7-1.png)<!-- -->
\#\# Export your first scatterplot to your project directory using
ggsave.

``` r
ggsave("scatter_plot.pdf", height = 4, width = 6)
```

    ## Warning: Removed 2 rows containing missing values (geom_point).
